"""Shared dataclasses used by the IoT, blockchain, and simulation modules."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum
from typing import Any


class TransactionType(StrEnum):
    """Transaction types generated by the shared simulation stream."""

    TRANSFER = "transfer"
    IOT_DATA = "iot_data"
    FEEDBACK = "feedback"


class TransactionStatus(StrEnum):
    """Lifecycle states for network-specific transactions."""

    PENDING = "pending"
    CONFIRMED = "confirmed"
    REJECTED = "rejected"
    FAILED = "failed"


@dataclass(frozen=True, slots=True)
class DeviceProfile:
    """Immutable device configuration shared by both network engines."""

    database_id: int
    device_key: str
    display_name: str | None
    initial_balance: float
    precision: float
    execution_cost: float
    data_rate: float
    profit_expectation: float
    parameters: dict[str, Any] = field(default_factory=dict)
    group_name: str | None = None


@dataclass(slots=True)
class NetworkDeviceState:
    """Mutable economic and participation state for one network."""

    profile: DeviceProfile
    balance: float
    active: bool = True
    reserved_balance: float = 0
    cumulative_reward: float = 0
    cumulative_penalties: float = 0
    cumulative_cost: float = 0
    reputation_score: float = 0
    contribution_score: float = 0
    useful_contribution_count: int = 0
    last_participation_signal: float | None = None
    feedback_score: float = 0
    submitted_transactions: int = 0
    confirmed_transactions: int = 0
    rejected_transactions: int = 0
    data_submissions: int = 0
    churn_reason: str | None = None

    @property
    def cumulative_profit(self) -> float:
        """Return reward income minus device and transaction costs."""
        return (
            self.cumulative_reward
            - self.cumulative_penalties
            - self.cumulative_cost
        )

    @property
    def available_balance(self) -> float:
        """Return funds not reserved by pending transfers."""
        return self.balance - self.reserved_balance

    @property
    def average_data_profit(self) -> float | None:
        """Return average net profit per submitted IoT data item."""
        if self.data_submissions == 0:
            return None
        return self.cumulative_profit / self.data_submissions


@dataclass(slots=True)
class ExternalOpportunity:
    """One shared opportunity that a device may choose to act upon."""

    sequence_number: int
    scheduled_at_ms: int
    event_type: TransactionType
    sender_device_id: int | None
    target_device_id: int | None
    amount: float = 0
    payload: dict[str, Any] = field(default_factory=dict)
    database_id: int | None = None

    def to_database_record(self, simulation_id: int) -> dict[str, Any]:
        """Persist the opportunity using the existing event table."""
        return {
            "simulation_id": simulation_id,
            "sequence_number": self.sequence_number,
            "scheduled_at_ms": self.scheduled_at_ms,
            "event_type": self.event_type.value,
            "sender_device_id": self.sender_device_id,
            "target_device_id": self.target_device_id,
            "amount": self.amount,
            "payload_json": self.payload,
        }

    def to_plugin_context(self) -> dict[str, Any]:
        """Return a JSON-compatible opportunity representation."""
        return {
            "sequence_number": self.sequence_number,
            "scheduled_at_ms": self.scheduled_at_ms,
            "event_type": self.event_type.value,
            "sender_device_id": self.sender_device_id,
            "target_device_id": self.target_device_id,
            "amount": self.amount,
            "payload": dict(self.payload),
        }

    def to_action(self) -> DeviceAction:
        """Create the default action corresponding to this opportunity."""
        return DeviceAction(
            sequence_number=self.sequence_number,
            scheduled_at_ms=self.scheduled_at_ms,
            event_type=self.event_type,
            sender_device_id=self.sender_device_id,
            target_device_id=self.target_device_id,
            amount=self.amount,
            payload=dict(self.payload),
            database_id=self.database_id,
        )

    def copy(self) -> ExternalOpportunity:
        """Return an arm-local copy with an independent payload."""
        return ExternalOpportunity(
            sequence_number=self.sequence_number,
            scheduled_at_ms=self.scheduled_at_ms,
            event_type=self.event_type,
            sender_device_id=self.sender_device_id,
            target_device_id=self.target_device_id,
            amount=self.amount,
            payload=dict(self.payload),
            database_id=self.database_id,
        )


@dataclass(slots=True)
class DeviceAction:
    """An action a device actually chose to submit to a network model."""

    sequence_number: int
    scheduled_at_ms: int
    event_type: TransactionType
    sender_device_id: int | None
    target_device_id: int | None
    amount: float = 0
    payload: dict[str, Any] = field(default_factory=dict)
    database_id: int | None = None

    def to_database_record(self, simulation_id: int) -> dict[str, Any]:
        """Compatibility helper for callers that persist actions."""
        return {
            "simulation_id": simulation_id,
            "sequence_number": self.sequence_number,
            "scheduled_at_ms": self.scheduled_at_ms,
            "event_type": self.event_type.value,
            "sender_device_id": self.sender_device_id,
            "target_device_id": self.target_device_id,
            "amount": self.amount,
            "payload_json": self.payload,
        }

    def to_plugin_context(self) -> dict[str, Any]:
        """Return a JSON-compatible action representation."""
        return {
            "sequence_number": self.sequence_number,
            "scheduled_at_ms": self.scheduled_at_ms,
            "event_type": self.event_type.value,
            "sender_device_id": self.sender_device_id,
            "target_device_id": self.target_device_id,
            "amount": self.amount,
            "payload": dict(self.payload),
        }


@dataclass(frozen=True, slots=True)
class NonParticipationRecord:
    """Record that an opportunity did not produce a device action."""

    opportunity_sequence: int
    scheduled_at_ms: int
    device_id: int | None
    reason: str


SimulationEvent = DeviceAction


@dataclass(slots=True)
class NetworkTransaction:
    """Network-specific outcome of processing a shared event."""

    transaction_hash: str
    transaction_type: TransactionType
    status: TransactionStatus
    event_id: int | None
    sender_device_id: int | None
    target_device_id: int | None
    submitted_at_ms: int
    amount: float = 0
    fee: float = 0
    reward: float = 0
    confirmed_at_ms: int | None = None
    payload: dict[str, Any] = field(default_factory=dict)
    rejection_reason: str | None = None
    block_height: int | None = None
    reward_override: float | None = None


@dataclass(slots=True)
class Block:
    """A mined block and its confirmed transactions."""

    height: int
    block_hash: str
    previous_hash: str | None
    mined_at_ms: int
    nonce: int
    difficulty: int
    transaction_hashes: list[str]
    total_fees: float
    block_reward: float
    mining_duration_ms: float
    miner_address: str = "virtual-miner"


@dataclass(slots=True)
class MiningJob:
    """A block candidate currently being mined in virtual time."""

    height: int
    started_at_ms: int
    completes_at_ms: int
    nonce: int
    candidate_hash: str
    previous_hash: str | None
    transactions: list[NetworkTransaction]
    mining_duration_ms: float
